### ISSUE TITLE
🪣 onboarding for mobile 

### ISSUE THREAD

**Issue by sachben91** [hicommonwealth/commonwealth#10247]
### Description

Onboarding for users on mobile app. Only users who are opening the app for the first time should see these.

For clarity these should be added to the https://github.com/hicommonwealth/commonwealth-mobile2 Repo

### Project Owner

@dillchen

### PRD

see below figma 

### Tasks

- [x] #10283
- [x] #10250 
- [x] #10251 
- [x] #10252  
- [x] #10253  
- [x] #10254 

### Eng Requirements

- [x] Animations - React Native
- [ ] Login - React Native
-- SSO - React Native
-- Wallet Connect - WebView?
- [x] Notification - WebView (no desire to do TRPC in ReactNative) 
- [x] Set Username  - WebView
- [x] Community Selection  - WebView
- [x] Referral Link - WebView

@burtonator , says we don't want react-native screens, we should just use react and then detect first time mobile usage using whatever pattern @burtonator has established

### Design Links

[Figma ](https://www.figma.com/design/I5jbkBPzNrbYMHYQJb6CNY/Onboarding?node-id=1602-25580&node-type=canvas&t=ZQDXk8FF8nmtjMg4-0)

----
Debugging
- WalletConnect (Sabina, just not open the app)
-- Opens Random Browser and Does not Redirect (dillon Repro-ed)
- SSO Login (Apple + SMS Login)

**Comment by KaleemNeslit** [comment]
i discuss this with @burtonator  it better to hold it until we decide if we're going to handle onboarding in react-native.

**Comment by burtonator** [comment]
@KaleemNeslit  to be clear we can design these in react just make the adjustment for mobile.  We can discuss if you want.

**Comment by MuhammadKaleem171** [comment]
> @KaleemNeslit to be clear we can design these in react just make the adjustment for mobile. We can discuss if you want.

@burtonator  sure let connect and start working on it
