### ISSUE TITLE
Address Deduplication - Master Issue

### ISSUE THREAD

**Issue by CowMuon** [hicommonwealth/commonwealth#2793]
This is the main story for address deduplication.  Tasks here may be broken out into their own stories or atomic PRs, however this is the master issue for work completion. 

Full information can be found in [Address Refactoring TechSpec](https://www.notion.so/buildcommon/Address-Refactoring-Tech-Spec-5f0f21e54ce4415391017d2c4624af6f)

Tasks needed for completion: 
- [ ] Client: Refactor app logic to remove duplicate address creation. (This _should_ only affect 2 routes, login and join community)

Files that may (or may not) be affected: 
- [ ] login_selector.tsx
- [ ] controllers/server/profiles.ts
- [ ]
