### ISSUE TITLE
 Database Query Analysis & Optimization

### ISSUE THREAD

**Issue by NakulManchanda** [hicommonwealth/commonwealth#3429]
## Description
SequelizeConnectionAcquireTimeoutError - has occured **25K times since first seen**
Last seen six hours ago 

1390 - in last 24hrs
3878 - in last 7 days
8635 - in last 30 days

<img width="1269" alt="image" src="https://user-images.githubusercontent.com/4791635/231644188-18d973d6-4d0d-473d-9ea1-1d5ad74b0796.png">

**It could be some change within last month or two responsible for increased occurrence of this particular error**

## Acceptance Criteria
- No timeout or reduce count by factor of 100 or 1K

## Wiki
- Setup & Analysis - Captured in Wiki
https://github.com/hicommonwealth/commonwealth/wiki/Database-Monitoring

# Related issues
Quick Summary - boils down to **three issues** for now each to be handled in a different way
**Identified three issues:**

- [x]  **Frequent Query:** **validateChain** is a middleware - get called large number of times - will tackle as mentioned here https://github.com/hicommonwealth/commonwealth/issues/3434

- [x] **Slow Query:** delete thread requires **deleting subscription** - slow cascade delete https://github.com/hicommonwealth/commonwealth/issues/3437

- [ ] **Slow Query:** **notificationread insert** happen more often as is a slow operation - probably need to pre-compute max or shard or partition table so query become lighter https://github.com/hicommonwealth/commonwealth/issues/3438

**Comment by NakulManchanda** [comment]
Two approaches to resolve the issue:
- Either debug particular scenario 
- or identify general slow queries which might be leading to timeouts
```

20 | ): Promise<[ChainInstance, string]> => {
-- | --
21 | const chain_id = params.chain \|\| params.chain_id;
22 | if (!chain_id) return [null, ChainCommunityErrors.ChainDNE];
23 | const chain = await models.Chain.findOne({
24 | where: {
25 | id: chain_id,
26 | },

```

**Comment by NakulManchanda** [comment]
There is very big discussion about causes of this error according to this github thread
https://github.com/sequelize/sequelize/issues/10858#issuecomment-572463988

**Comment by NakulManchanda** [comment]
Some helpful queries:

Top 10 queries - which referred to Chains
```SQL
SELECT calls, total_exec_time, query FROM pg_stat_statements where query like '%Chains%' ORDER BY total_exec_time DESC LIMIT 10;
```

Top Query - **total calls** `14321` | **total execution time** `8263667.200697999`
```SQL
SELECT "Subscription"."id", "Subscription"."subscriber_id", "Subscription"."category_id", "Subscription"."object_id", "Subscription"."is_active", "Subscription"."immediate_email", "Subscription"."chain_id", "Subscription"."offchain_thread_id", "Subscription"."offchain_comment_id", "Subscription"."snapshot_id", "Subscription"."created_at", "Subscription"."updated_at", "Thread"."id" AS "Thread.id", "Thread"."address_id" AS "Thread.address_id", "Thread"."title" AS "Thread.title", "Thread"."body" AS "Thread.body", "Thread"."plaintext" AS "Thread.plaintext", "Thread"."kind" AS "Thread.kind", "Thread"."stage" AS "Thread.stage", "Thread"."url" AS "Thread.url", "Thread"."topic_id" AS "Thread.topic_id", "Thread"."pinned" AS "Thread.pinned", "Thread"."chain" AS "Thread.chain", "Thread"."view_count" AS "Thread.view_count", "Thread"."read_only" AS "Thread.read_only", "Thread"."version_history" AS "Thread.version_history", "Thread"."snapshot_proposal" AS "Thread.snapshot_proposal", "Thread"."has_poll" AS "Thread.has_poll", "Thread"."canvas_action" AS "Thread.canvas_action", "Thread"."canvas_session" AS "Thread.canvas_session", "Thread"."canvas_hash" AS "Thread.canvas_hash", "Thread"."created_at" AS "Thread.created_at", "Thread"."updated_at" AS "Thread.updated_at", "Thread"."deleted_at" AS "Thread.deleted_at", "Thread"."last_commented_on" AS "Thread.last_commented_on", "Thread->Address"."id" AS "Thread.Address.id", "Thread->Address"."address" AS "Thread.Address.address", "Thread->Address"."chain" AS "Thread.Address.chain", "Thread->Address"."verified" AS "Thread.Address.verified", "Thread->Address"."keytype" AS "Thread.Address.keytype", "Thread->Address"."name" AS "Thread.Address.name", "Thread->Address"."last_active" AS "Thread.Address.last_active", "Thread->Address"."user_id" AS "Thread.Address.user_id", "Thread->Address"."is_councillor" AS "Thread.Address.is_councillor", "Thread->Address"."is_validator" AS "Thread.Address.is_validator", "Thread->Address"."ghost_address" AS "Thread.Address.ghost_address", "Thread->Address"."profile_id" AS "Thread.Address.profile_id", "Thread->Address"."wallet_id" AS "Thread.Address.wallet_id", "Thread->Address"."user_id" AS "Thread.Address.UserId", "Comment"."id" AS "Comment.id", "Comment"."chain" AS "Comment.chain", "Comment"."thread_id" AS "Comment.thread_id", "Comment"."parent_id" AS "Comment.parent_id", "Comment"."address_id" AS "Comment.address_id", "Comment"."text" AS "Comment.text", "Comment"."plaintext" AS "Comment.plaintext", "Comment"."version_history" AS "Comment.version_history", "Comment"."canvas_action" AS "Comment.canvas_action", "Comment"."canvas_session" AS "Comment.canvas_session", "Comment"."canvas_hash" AS "Comment.canvas_hash", "Comment"."created_at" AS "Comment.created_at", "Comment"."updated_at" AS "Comment.updated_at", "Comment"."deleted_at" AS "Comment.deleted_at", "Comment->Address"."id" AS "Comment.Address.id", "Comment->Address"."address" AS "Comment.Address.address", "Comment->Address"."chain" AS "Comment.Address.chain", "Comment->Address"."verified" AS "Comment.Address.verified", "Comment->Address"."keytype" AS "Comment.Address.keytype", "Comment->Address"."name" AS "Comment.Address.name", "Comment->Address"."last_active" AS "Comment.Address.last_active", "Comment->Address"."user_id" AS "Comment.Address.user_id", "Comment->Address"."is_councillor" AS "Comment.Address.is_councillor", "Comment->Address"."is_validator" AS "Comment.Address.is_validator", "Comment->Address"."ghost_address" AS "Comment.Address.ghost_address", "Comment->Address"."profile_id" AS "Comment.Address.profile_id", "Comment->Address"."wallet_id" AS "Comment.Address.wallet_id", "Comment->Address"."user_id" AS "Comment.Address.UserId", "Chain"."id" AS "Chain.id", "Chain"."chain_node_id" AS "Chain.chain_node_id", "Chain"."name" AS "Chain.name", "Chain"."discord_config_id" AS "Chain.discord_config_id", "Chain"."description" AS "Chain.description", "Chain"."token_name" AS "Chain.token_name", "Chain"."website" AS "Chain.website", "Chain"."discord" AS "Chain.discord", "Chain"."element" AS "Chain.element", "Chain"."telegram" AS "Chain.telegram", "Chain"."github" AS "Chain.github", "Chain"."default_symbol" AS "Chain.default_symbol", "Chain"."network" AS "Chain.network", "Chain"."base" AS "Chain.base", "Chain"."ss58_prefix" AS "Chain.ss58_prefix", "Chain"."icon_url" AS "Chain.icon_url", "Chain"."active" AS "Chain.active", "Chain"."stages_enabled" AS "Chain.stages_enabled", "Chain"."custom_stages" AS "Chain.custom_stages", "Chain"."custom_domain" AS "Chain.custom_domain", "Chain"."block_explorer_ids" AS "Chain.block_explorer_ids", "Chain"."collapsed_on_homepage" AS "Chain.collapsed_on_homepage", "Chain"."type" AS "Chain.type", "Chain"."substrate_spec" AS "Chain.substrate_spec", "Chain"."has_chain_events_listener" AS "Chain.has_chain_events_listener", "Chain"."default_summary_view" AS "Chain.default_summary_view", "Chain"."hide_projects" AS "Chain.hide_projects", "Chain"."terms" AS "Chain.terms", "Chain"."bech32_prefix" AS "Chain.bech32_prefix", "Chain"."admin_only_polling" AS "Chain.admin_only_polling", "Chain"."default_allow_permissions" AS "Chain.default_allow_permissions", "Chain"."default_deny_permissions" AS "Chain.default_deny_permissions" 
FROM "Subscriptions" AS "Subscription" 
LEFT OUTER JOIN "Threads" AS "Thread" ON "Subscription"."offchain_thread_id" = "Thread"."id" AND ("Thread"."deleted_at" IS NULL) 
LEFT OUTER JOIN "Addresses" AS "Thread->Address" ON "Thread"."address_id" = "Thread->Address"."id" 
LEFT OUTER JOIN "Comments" AS "Comment" ON "Subscription"."offchain_comment_id" = "Comment"."id" AND ("Comment"."deleted_at" IS NULL) 
LEFT OUTER JOIN "Addresses" AS "Comment->Address" ON "Comment"."address_id" = "Comment->Address"."id" 
LEFT OUTER JOIN "Chains" AS "Chain" ON "Subscription"."chain_id" = "Chain"."id" AND "Chain"."active" = true 
WHERE ("Subscription"."subscriber_id" = 844549)
```

**Comment by NakulManchanda** [comment]
**Using PGAdmin4 Dashboard:**
Server Activity - Widget is UI for `pg_stat_activity` it also displays locks, blocked on, running time, query type, query etc
 
![image](https://user-images.githubusercontent.com/4791635/231654143-69f905e2-8224-42b1-b265-046e0a2e4db6.png)

**Comment by NakulManchanda** [comment]
Slow queries - 
```SQL
DELETE FROM "Subscriptions" WHERE "offchain_thread_id" = $1

INSERT INTO "NotificationsRead" 
VALUES ($1, $2, $3, $4, (SELECT COALESCE(MAX(id), $5) + $6 FROM "NotificationsRead" WHERE user_id = $7))
, ($8, $9, $10, $11, (SELECT COALESCE(MAX(id), $12) + $13 FROM "NotificationsRead" WHERE user_id = $14))
, ($15, $16, $17, $18, (SELECT COALESCE(MAX(id), $19) + $20 FROM "NotificationsRead" WHERE user_id = $21))
, ($22, $23, $24, $25, (SELECT COALESCE(MAX(id), $26) + $27 FROM "NotificationsRead" WHERE user_id = $28))
, ($29, $30, $31, $32, (SELECT COALESCE(MAX(id), $33) + $34 FROM "NotificationsRead" WHERE user_id = $35))
, ($36, $37, $38, $39, (SELECT COALESCE(MAX(id), $40) + $41 FROM "NotificationsRead" WHERE user_id = $42))
, ($43, $44, $45, $46, (SELECT COALESCE(MAX(id), $47) + $48 FROM "NotificationsRead" WHERE user_id = $49))
, ($8933, $8934, $8935, $8936, (SELECT COALESCE(MAX(id), $8937) + $8938 FROM "NotificationsRead" WHERE user_id = $8939))
, ($8940, $8941, $8942, $8943, (SELECT COALESCE(MAX(id), $8944) + $8945 FROM "NotificationsRead" WHERE user_id = $8946))
, ($8947, $8948, $8949, $8950, (SELECT COALESCE(MAX(id), $8951) + $8952 FROM "NotificationsRead" WHERE user_id = $8953))
```

<img width="1095" alt="image" src="https://user-images.githubusercontent.com/4791635/231815997-a1a97d2c-cfd7-4f88-8fcf-3486d4e0bda7.png">

**Comment by NakulManchanda** [comment]
Quick Summary - boils down to three issues for now each to be handled in a different way
**Identified three issues:**
 - **validateChain** is a middleware - get called large number of times - will tackle as mentioned here https://github.com/hicommonwealth/commonwealth/issues/3434
- delete thread requires **deleting subscription** - slow cascade delete https://github.com/hicommonwealth/commonwealth/issues/3437
- **notificationread insert** happen more often as is a slow operation - probably need to pre-compute max or shard or partition table so query become lighter https://github.com/hicommonwealth/commonwealth/issues/3438

**Comment by NakulManchanda** [comment]
`viewSubscriptions` Query

```
SELECT "Subscription"."id", "Subscription"."subscriber_id", "Subscription"."category_id", "Subscription"."object_id", 
"Subscription"."is_active", "Subscription"."immediate_email", "Subscription"."chain_id", 
"Subscription"."offchain_thread_id", "Subscription"."offchain_comment_id", "Subscription"."snapshot_id", 
"Subscription"."created_at", "Subscription"."updated_at", "Thread"."id" AS "Thread.id", 
"Thread"."address_id" AS "Thread.address_id", "Thread"."title" AS "Thread.title", 
"Thread"."body" AS "Thread.body", "Thread"."plaintext" AS "Thread.plaintext", "Thread"."kind" AS "Thread.kind", 
"Thread"."stage" AS "Thread.stage", "Thread"."url" AS "Thread.url", "Thread"."topic_id" AS "Thread.topic_id",
 "Thread"."pinned" AS "Thread.pinned", "Thread"."chain" AS "Thread.chain", "Thread"."view_count" AS "Thread.view_count", 
 "Thread"."read_only" AS "Thread.read_only", "Thread"."version_history" AS "Thread.version_history", 
 "Thread"."links" AS "Thread.links", "Thread"."has_poll" AS "Thread.has_poll", 
 "Thread"."canvas_action" AS "Thread.canvas_action",
  "Thread"."canvas_session" AS "Thread.canvas_session", 
  "Thread"."canvas_hash" AS "Thread.canvas_hash", "Thread"."created_at" AS "Thread.created_at", 
  "Thread"."updated_at" AS "Thread.updated_at", "Thread"."deleted_at" AS "Thread.deleted_at", 
  "Thread"."last_commented_on" AS "Thread.last_commented_on",
   "Thread->Address"."id" AS "Thread.Address.id", "Thread->Address"."address" AS "Thread.Address.address",
    "Thread->Address"."chain" AS "Thread.Address.chain", "Thread->Address"."verified" AS "Thread.Address.verified", 
    "Thread->Address"."keytype" AS "Thread.Address.keytype", 
    "Thread->Address"."name" AS "Thread.Address.name",
     "Thread->Address"."last_active" AS "Thread.Address.last_active", "Thread->Address"."user_id" AS "Thread.Address.user_id", 
     "Thread->Address"."is_councillor" AS "Thread.Address.is_councillor", "Thread->Address"."is_validator" AS "Thread.Address.is_validator", "Thread->Address"."ghost_address" AS "Thread.Address.ghost_address",
      "Thread->Address"."profile_id" AS "Thread.Address.profile_id", "Thread->Address"."wallet_id" AS "Thread.Address.wallet_id", "Thread->Address"."user_id" AS "Thread.Address.UserId", "Comment"."id" AS "Comment.id", "Comment"."chain" AS "Comment.chain", "Comment"."thread_id" AS "Comment.thread_id", 
      "Comment"."parent_id" AS "Comment.parent_id", "Comment"."address_id" AS "Comment.address_id", "Comment"."text" AS "Comment.text", "Comment"."plaintext" AS "Comment.plaintext", "Comment"."version_history" AS "Comment.version_history", "Comment"."canvas_action" AS "Comment.canvas_action", "Comment"."canvas_session" AS "Comment.canvas_session", "Comment"."canvas_hash" AS "Comment.canvas_hash", "Comment"."created_at" AS "Comment.created_at", "Comment"."updated_at" AS "Comment.updated_at", "Comment"."deleted_at" AS "Comment.deleted_at", "Comment->Address"."id" AS "Comment.Address.id", "Comment->Address"."address" AS "Comment.Address.address", "Comment->Address"."chain" AS "Comment.Address.chain", "Comment->Address"."verified" AS "Comment.Address.verified", "Comment->Address"."keytype" AS "Comment.Address.keytype", "Comment->Address"."name" AS "Comment.Address.name", "Comment->Address"."last_active" AS "Comment.Address.last_active", "Comment->Address"."user_id" AS "Comment.Address.user_id", "Comment->Address"."is_councillor" AS "Comment.Address.is_councillor", "Comment->Address"."is_validator" AS "Comment.Address.is_validator", "Comment->Address"."ghost_address" AS "Comment.Address.ghost_address", "Comment->Address"."profile_id" AS "Comment.Address.profile_id", "Comment->Address"."wallet_id" AS "Comment.Address.wallet_id", "Comment->Address"."user_id" AS "Comment.Address.UserId", "Chain"."id" AS "Chain.id", "Chain"."chain_node_id" AS "Chain.chain_node_id", "Chain"."name" AS "Chain.name", "Chain"."discord_config_id" AS "Chain.discord_config_id", "Chain"."description" AS "Chain.description", "Chain"."token_name" AS "Chain.token_name", "Chain"."website" AS "Chain.website", "Chain"."discord" AS "Chain.discord", "Chain"."element" AS "Chain.element", "Chain"."telegram" AS "Chain.telegram", "Chain"."github" AS "Chain.github", "Chain"."default_symbol" AS "Chain.default_symbol", "Chain"."network" AS "Chain.network", "Chain"."base" AS "Chain.base", "Chain"."ss58_prefix" AS "Chain.ss58_prefix", "Chain"."icon_url" AS "Chain.icon_url", "Chain"."active" AS "Chain.active", "Chain"."stages_enabled" AS "Chain.stages_enabled", "Chain"."custom_stages" AS "Chain.custom_stages", "Chain"."custom_domain" AS "Chain.custom_domain", "Chain"."block_explorer_ids" AS "Chain.block_explorer_ids", "Chain"."collapsed_on_homepage" AS "Chain.collapsed_on_homepage", "Chain"."type" AS "Chain.type", "Chain"."substrate_spec" AS "Chain.substrate_spec", "Chain"."has_chain_events_listener" AS "Chain.has_chain_events_listener", "Chain"."default_summary_view" AS "Chain.default_summary_view", "Chain"."default_page" AS "Chain.default_page", "Chain"."has_homepage" AS "Chain.has_homepage", "Chain"."hide_projects" AS "Chain.hide_projects", "Chain"."terms" AS "Chain.terms", "Chain"."bech32_prefix" AS "Chain.bech32_prefix", "Chain"."admin_only_polling" AS "Chain.admin_only_polling", "Chain"."default_allow_permissions" AS "Chain.default_allow_permissions", "Chain"."default_deny_permissions" AS "Chain.default_deny_permissions", "Chain"."category" AS "Chain.category", "Chain"."created_at" AS "Chain.created_at", "Chain"."updated_at" AS "Chain.updated_at" 
      FROM "Subscriptions" AS "Subscription" 
      LEFT OUTER JOIN "Threads" AS "Thread" ON "Subscription"."offchain_thread_id" = "Thread"."id" AND ("Thread"."deleted_at" IS NULL) 
      LEFT OUTER JOIN "Addresses" AS "Thread->Address" ON "Thread"."address_id" = "Thread->Address"."id" 
      LEFT OUTER JOIN "Comments" AS "Comment" ON "Subscription"."offchain_comment_id" = "Comment"."id" AND ("Comment"."deleted_at" IS NULL) 
      LEFT OUTER JOIN "Addresses" AS "Comment->Address" ON "Comment"."address_id" = "Comment->Address"."id" 
      LEFT OUTER JOIN "Chains" AS "Chain" ON "Subscription"."chain_id" = "Chain"."id" AND "Chain"."active" = true 
 WHERE "Subscription"."subscriber_id" = 114041;


```

**Comment by NakulManchanda** [comment]
As mentioned on slack by @timolegros 
https://commonxyz.slack.com/archives/C04TPN0J9GX/p1684156694645079

i guess being refer to rollbar timeouts!

**Comment by NakulManchanda** [comment]
Disk space by each column:

<img width="248" alt="image" src="https://github.com/hicommonwealth/commonwealth/assets/4791635/b7655364-3f68-47eb-a919-7ff89d626747">


```
SELECT * FROM (SELECT 'id' AS column_name, sum(pg_column_size(id)) AS size_bytes FROM "Threads" UNION ALL
 SELECT 'address_id' AS column_name, sum(pg_column_size(address_id)) AS size_bytes FROM "Threads" UNION ALL
 SELECT 'title' AS column_name, sum(pg_column_size(title)) AS size_bytes FROM "Threads" UNION ALL
 SELECT 'body' AS column_name, sum(pg_column_size(body)) AS size_bytes FROM "Threads" UNION ALL
 SELECT 'created_at' AS column_name, sum(pg_column_size(created_at)) AS size_bytes FROM "Threads" UNION ALL
 SELECT 'updated_at' AS column_name, sum(pg_column_size(updated_at)) AS size_bytes FROM "Threads" UNION ALL
 SELECT 'deleted_at' AS column_name, sum(pg_column_size(deleted_at)) AS size_bytes FROM "Threads" UNION ALL
 SELECT 'chain' AS column_name, sum(pg_column_size(chain)) AS size_bytes FROM "Threads" UNION ALL
 SELECT 'pinned' AS column_name, sum(pg_column_size(pinned)) AS size_bytes FROM "Threads" UNION ALL
 SELECT 'kind' AS column_name, sum(pg_column_size(kind)) AS size_bytes FROM "Threads" UNION ALL
 SELECT 'url' AS column_name, sum(pg_column_size(url)) AS size_bytes FROM "Threads" UNION ALL
 SELECT 'version_history' AS column_name, sum(pg_column_size(version_history)) AS size_bytes FROM "Threads" UNION ALL
 SELECT 'read_only' AS column_name, sum(pg_column_size(read_only)) AS size_bytes FROM "Threads" UNION ALL
 SELECT 'topic_id' AS column_name, sum(pg_column_size(topic_id)) AS size_bytes FROM "Threads" UNION ALL
 SELECT 'plaintext' AS column_name, sum(pg_column_size(plaintext)) AS size_bytes FROM "Threads" UNION ALL
 SELECT 'stage' AS column_name, sum(pg_column_size(stage)) AS size_bytes FROM "Threads" UNION ALL
 SELECT 'has_poll' AS column_name, sum(pg_column_size(has_poll)) AS size_bytes FROM "Threads" UNION ALL
 SELECT 'last_commented_on' AS column_name, sum(pg_column_size(last_commented_on)) AS size_bytes FROM "Threads" UNION ALL
 SELECT '_search' AS column_name, sum(pg_column_size(_search)) AS size_bytes FROM "Threads" UNION ALL
 SELECT 'canvas_action' AS column_name, sum(pg_column_size(canvas_action)) AS size_bytes FROM "Threads" UNION ALL
 SELECT 'canvas_session' AS column_name, sum(pg_column_size(canvas_session)) AS size_bytes FROM "Threads" UNION ALL
 SELECT 'canvas_hash' AS column_name, sum(pg_column_size(canvas_hash)) AS size_bytes FROM "Threads" UNION ALL
 SELECT 'view_count' AS column_name, sum(pg_column_size(view_count)) AS size_bytes FROM "Threads" UNION ALL
 SELECT 'links' AS column_name, sum(pg_column_size(links)) AS size_bytes FROM "Threads") A
ORDER BY 2 DESC
```

**Comment by jnaviask** [comment]
@NakulManchanda feel free to open a ticket to clean up viewSubscriptions. Much of its data is not needed + the call can take up to 5s (!!).

**Comment by NakulManchanda** [comment]
Here is ticket https://github.com/hicommonwealth/commonwealth/issues/4089
Was already looking into this endpoint last week, before switching focus to other obvious improvements.

`viewSubscriptions` is on top of the list for improvements, since its the slowest endpoint on forum pages

**Comment by NakulManchanda** [comment]
This comment for `viewSubscriptions` is addressed here:
In exclude attribute PR
https://github.com/hicommonwealth/commonwealth/issues/3429#issuecomment-1552327071

**Comment by NakulManchanda** [comment]
Current long queries:
- `/api/viewSubscriptions`
- `/api/bulkOffchain?chain=osmosis`
- `/api/threads?active=true&chain=osmosis&threads_per_topic=3`
<img width="947" alt="image" src="https://github.com/hicommonwealth/commonwealth/assets/4791635/46895afc-218b-4a9c-a9a0-9fde0c942c2e">
