### ISSUE TITLE
Redis Cache for performance of DB and frontend

### ISSUE THREAD

**Issue by NakulManchanda** [hicommonwealth/commonwealth#3558]
## Caching Design

https://github.com/hicommonwealth/commonwealth/wiki/caching

## Description
We can utilize caching in three broader areas:
- cache sql query response eg. `User.cache().findAll`
- caching at route level - response from route such as `/api/status`
- caching response from external points like blockchain - `cosmosProxy.js`

There are two choices for caching 
- in-memory `node-cache`
- distributed - `node-redis`

- As we have multiple app servers on backend
  , distributed cache could be a good idea, as multiple servers can take advantage of cached responses
- redis cache we may need manual clearing of cache, in memory cache, clears itself out on redeployment
- persistent caching in redis can help during releases we can still serve previously cached response

## Acceptance Criteria
- all caching endpoints must support configurable TTL
- must support path to manual invlaidation on updates/inserts

## Related Issues:

- [x] Setup Caching Helper Class - https://github.com/hicommonwealth/commonwealth/pull/3492
- [ ] Cache Frequent Endpoints - /globalUserActivity, /api/status - https://github.com/hicommonwealth/commonwealth/issues/3813 https://github.com/hicommonwealth/commonwealth/pull/3864 - /api/status https://github.com/hicommonwealth/commonwealth/pull/3892 - /viewUserActivity
- [x] Cache Block Cosmos - https://github.com/hicommonwealth/commonwealth/issues/3151
- [ ] Cache Frequent Database Queries -  https://github.com/hicommonwealth/commonwealth/issues/3680
https://github.com/hicommonwealth/commonwealth/pull/3862
https://github.com/hicommonwealth/commonwealth/issues/3866

**Comment by dillchen** [comment]
@NakulManchanda for the second bullet point "cache frequent endpoints"

- /globalUserActivity (I see the ticket / PR for this one) => ty
- /api/status" => is this also ticketed? also would love the story point estimate there as well

Solving the second item (would dramatically improve product / user experience) => 

<img width="1005" alt="image" src="https://user-images.githubusercontent.com/5334557/236058101-a7d44b97-1c34-4878-a36a-017970c57b1c.png">

**Comment by dillchen** [comment]
Is this the ticket? https://github.com/hicommonwealth/commonwealth/issues/2483

**Comment by NakulManchanda** [comment]
Hi,
We wanted to rollout redis slowly.
We didn't go very aggressive.

- This is on our list, we will be closing some of these issue very soon.
   - specifically for `/api/status`  - due to user specific data in call we blocked it in last rollout
      - yes this one https://github.com/hicommonwealth/commonwealth/issues/2483
      - https://github.com/hicommonwealth/commonwealth/issues/3680 - this will also help with caching
 
These are live items on board! 
FYI @jnaviask

**Comment by dillchen** [comment]
Very helpful context, thank you
