### ISSUE TITLE
[Push Notifs] - Implement Push Notifications (for ToDesktop, Capacitor, Browser, and PWA)

### ISSUE THREAD

**Issue by dillchen** [hicommonwealth/commonwealth#4248]
## Description
Implement a system to send push notifications to users based on their preferences through different channels, including browser notifications, desktop notifications, and mobile push notifications using Capacitor.

[Current detailed tentative spec here, may be used as a reference or superseded](https://www.notion.so/buildcommon/Title-Implement-Push-Notifications-for-Browser-Desktop-and-Mobile-e15a06b52a7f4d3e91f3a307ca8cd0f1?pvs=4)

**Please note, this could be broken down into several tickets, at the very least, one for each delivery mechanism**

## Engineering Requirements
- [x] Adjust the client-side to handle notification preferences and update the UI on the Notification Settings Page.
- [x] Set up Firebase Cloud Messaging (FCM) for Android devices and Apple Push Notification service (APNs) for iOS devices.
- [x] Create or extend model for storing notification preferences and preferences/tokens for each channel, potentially on each subscription. Tracked in #4579. 
- [x] Let users set which delivery mechanisms they want to use #4595 #4596 
- [x] Let users choose which notifications go to which mechanism #4604 
- [x] Create a utility file `utils/pushNotifications.ts` for sending push notifications.
- [x] Update the `emitNotifications` function to support push notifications and integrate the utility functions created in step 3 to send the notifications.
- [x] Fulfull additional product and design requests #4849
- [ ] Migrate `SubscriptionDeliveries` to new data model
- [ ] Update the eng requirements per spec

## Deploy Requirements
- [ ] Ensure FCM Update and set properly
- [ ] Ensure ToDesktop Configurations are considered
- [ ] Ensure Good Internal Documentation around API Keys and more, and update how we set (maybe rotating serviceAccountKey.json),
- [ ] Set up production keys and store in the normal manner

## Acceptance Criteria
- Users should be able to receive push notifications based on their preferences through browser, desktop, and mobile channels.
- The system should send push notifications without requiring a separate socket service.
- Notification preferences should be easily adjustable by users.
