### ISSUE TITLE
Pinned threads

### ISSUE THREAD

**Issue by raykyri** [hicommonwealth/commonwealth#489]
We should add a feature to pin threads in a community so important threads can be maintained at the top.

This should be relatively simple to start with (i.e. there is only one type of pinning, and it applies both within tags and within the larger community).

- Add a menu item for pinning or unpinning threads. Menu item should read "Pin thread" or "Unpin thread"

![image](https://user-images.githubusercontent.com/1273926/89842259-f3e16b00-db29-11ea-998d-039f6a0a2922.png)

(Would also be nice to visually separate out the admin actions in this menu, from the actions that both a regular user or admin can take...)

- When a thread is pinned, we should show a pinned icon on the left of the DiscussionRow. No change to the view_proposal page is necessary

![image](https://user-images.githubusercontent.com/1273926/89842210-d7453300-db29-11ea-852d-2e2283149baa.png)

- Pinning a thread makes it appear at the top of the community homepage, as well as at the top of the tag it is pinned to
- Pinned threads should be ordered by the date they were created, with oldest threads first
- Only admins and mods should be able to pin threads
- Pinned threads should always be loaded when the discussion listing is initially loaded, even if they would not normally appear that way. Paging in more threads should not break this, nor cause pinned threads to show up with duplicates. This should be handled in a sensible way on the backend, i.e. without weird special casing

**Comment by zakhap** [comment]
> Pinned threads should always be loaded when the discussion listing is initially loaded, even if they would not normally appear that way. Paging in more threads should not break this, nor cause pinned threads to show up with duplicates. This should be handled in a sensible way on the backend, i.e. without weird special casing
@raykyri what do you mean by this bullet? "not normally appear that way" and "weird special casing" in particular

**Comment by zakhap** [comment]
### TODOs: 

This should be relatively simple to start with (i.e. there is only one type of pinning, and it applies both within tags and within the larger community).

- [ ] Add a menu item for pinning or unpinning threads. Menu item should read "Pin thread" or "Unpin thread"
- [ ] (Would also be nice to visually separate out the admin actions in this menu, from the actions that both a regular user or admin can take...)
- [ ] When a thread is pinned, we should show a pinned icon on the left of the DiscussionRow. No change to the view_proposal page is necessary
- [ ] Pinning a thread makes it appear at the top of the community homepage, as well as at the top of the tag it is pinned to
- [ ] Pinned threads should be ordered by the date they were created, with oldest threads first
- [ ] Only admins and mods should be able to pin threads
- [ ] Pinned threads should always be loaded when the discussion listing is initially loaded, even if they would not normally appear that way. Paging in more threads should not break this, nor cause pinned threads to show up with duplicates. This should be handled in a sensible way on the backend, i.e. without weird special casing
