### ISSUE TITLE
Implement Gating API

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#4953]
## Description

This is a master ticket for the platform engineering required for the gating feature. This ticket defines the main interface that we will expose for gating as an API, ideally usable both by internal and external developers.

## Subtasks
To be broken into separate tickets as needed:
- [x] Implement stub interfaces for Groups routes. (#5013)
- [x] Using Requirements stubs (#4952), implement stub interfaces for Groups controller. (#5014)
- [x] Write unit tests for Groups controller. (#5015)
- [x] Write migrations + models for Groups and Memberships tables. (#5019)
- [x] Implement Groups controller, using Requirements adapter, including JSON schema validation logic. (#5025)
- [x] Write migration for transforming Topics table columns from token_threshold to group ids. (#5027)
- [x] Implement routes that rely on the Groups controller to implement specced functionality. (#5028)
- [x] API tests for Groups routes (#5029)

### Add Groups and Memberships tables
 
Groups Schema (note that RequirementsJSON definition comes from #4952 and that MetadataJSON is not defined at the database level, just at the interface level):

```
MetadataJSON:
{
  name: string;
  description: string;
  required_requirements?: number; // undefined = all
  membership_ttl?: number; // seconds for Membership to be stale -- what is default?
}

Group:
{
  id: number;
  chain_id: string; // reference to community -- indexed
  metadata: MetadataJSON;
  requirements: RequirementsJSON; // must pass above schema + validation

  // ORM-maintained columns
  created_at: Date;
  updated_at: Date;
}
```

Membership schema:
```
{
  group_id: number;   // fk: Groups
  address_id: number; // fk: Addresses (easier property querying than string)
  last_checked: Date;
}
```

### Add migration to convert token_threshold on topics into Group definitions.

Product requirements:
  - Migration should do two things:
    - For each unique token threshold within a community, create a Group with a Requirement defined by the threshold information. For Each topic with the same threshold, set each Topic’s to the same, respective Group.
        - For example, if an ERC20 community has 2 different thresholds set (“10 tokens” for X topic, and “2 tokens” for Y topics), create 2 different Groups each with their own requirement using the thresholds; Group 1 of Requirement Type “ERC20”, contract pulled from community, Chain pulled from ChainNode, and greater than or equal to “10 tokens”; same for Group 2 but “2 tokens”. For Y, Topics they should all be set to Group 2.
        - For “Cosmos” communities with Thresholds set, use the “Cosmos Base Token” Requirement Type for the Groups’ Requirements.
    - Remove “Threshold” from Topic Model.

### Implement/update the following routes:
  - **CreateGroup**: `POST /groups`
    - Access: Community Admin
    - Must validate the provided requirements against the JSON schema + also perform source validation
    - Limited to 20 groups per community
    - May also update Topics table to add group id as selected in form
    - Interface:
        
        ```tsx
        // request
        {
          jwt: string;
          chain_id: string;
          metadata: MetadataJSON;
          requirements: RequirementsJSON;
          topics?: number[]; // updates topics to apply group
        }
        
        // response
        Group
        ```
        
- **UpdateGroup**: `PUT /groups/:id`
    - Access: Community Admin
    - Clears the group membership
    - Request and response are same interface as CreateGroup
- **DeleteGroup**: `DELETE /groups/:id`
    - Access: Community Admin
    - Empty request body and empty success response
- **GetGroups**: `GET /groups?chain_id=ethereum&members=true&address=0x1234`
    - Access: Public
    - Get all groups in a community (requirements / metadata)
    - Optionally pass `members` query param to also include members in the payload
        - Gets all members in all groups in a community
        - For groups display on members page
    - Optionally pass `address` query param to return only groups/memberships associated with the specified address
        - Get current memberships for current user in all groups in a community
        - Current membership data, live or stale
    - Interface
    
    ```tsx
    // response
    {
      id: number;
      chain_id: string;
      metadata: MetadataJSON;
      requirements: RequirementsJSON;
    	members?: {
    	  group_id: number;
    	  address_id: number;
    	  last_checked: Date;
    	}[]
    }[]
    ```
    
- **RefreshMemberships**: `PUT /refresh-memberships`
    - Access: Member
    - Refresh stale memberships for current user in all groups in a community
    - Update membership DB objects against blockchains as needed + return updated results
- Write routes (any mutation within a topic): need to check membership status
    - CreateThread
    - CreateComment
    - CreateReaction

## Open Questions
- Should we store "no" results in Memberships table? Or what is another caching strategy to avoid constant rechecking?
- Should we store created_at/updated_at fields on Memberships table? In general, is Memberships table schema sufficient?
- In general, how will we handle caching and updating of group information? Scheduled job, lazy/as-needed, etc? Should update ticket with where we land.
- How can we represent different TTLs/stale times in the group metadata? Can different types of rules have different TTLs (e.g. AllowList taking effect immediately, vs threshold having significant time to stale)?

**Comment by rbennettcw** [comment]
Clarifications:
- Memberships would have an `allowed: boolean` property, so they represent both members and non-members– but only those who attempted to view the community (so the table doesn't get too large). We can have a scheduled job to clean up rejected memberships.
- Created/Updated columns for memberships doesn't seem to be necessary so far. We only care about the `last_checked` column.
- Memberships are loaded on the fly when a user views a community (via `/refresh-membership` route) and when a user performs a mutation action such as create thread or create comment.
- To accommodate instant effectiveness for the allow list, we can have the "check logic" *always* check the allowlist before performing any other checks.

Sequence diagram which illustrates the On-The-Fly workflow.

![Image](https://github.com/hicommonwealth/commonwealth/assets/126922418/34fceb78-f617-4b81-9aa3-b11f85f23686)
