### ISSUE TITLE
🪣 Create Community V1

### ISSUE THREAD

**Issue by sachben91** [hicommonwealth/commonwealth#5631]
## Description
Users who attempt to create communities on Common are likely to drop off while filling out the create community form because there is a lack of clarity on what information they are supposed to provide and how that affects the community they create. With Create Community V1, **we want to provide the user with a clear, concise, and short process to create a community on Common.** 

The **business goal** with Create Community is to increase the number of self-created communities on Common, which in the last quarter was in the single digits. Currently, users depend on growth team members to guide them through the Create Community flow. 

[PRD for the whole project (includes more than just V1)](https://www.notion.so/buildcommon/Create-Community-V1-40693cf5ca9e482dae368b13703b8583)

## Project Owner
Product manager: Sachin Benny 
Product designer: Jared Bell 

## Product specs
Create Community is separated into two steps - selecting the community type and providing basic information about the community they are trying to create. There is also an intermediate step in between the two where the user signs in or connects a wallet.
- [ ] https://github.com/hicommonwealth/commonwealth/issues/5633 : On this screen the user will select the ecosystem that their community will exist in. The options are Ethereum, Solana, Plygon, and Cosmos. The ecosystem that the user selects affects the intermediate step. They will be prompted to connect a wallet or use a sign in that is compatible with the ecosystem that is selected. (more details in sub ticket)
- [ ] https://github.com/hicommonwealth/commonwealth/issues/5636 : On this screen the user is prompted to provide a name for their community, description, a logo and other optional details such as social links (more details in sub ticket) 
- [ ] https://github.com/hicommonwealth/commonwealth/issues/5647: This is the page that the user is taken to once they have finished the required steps
