### ISSUE TITLE
🪣 Backend Changes For Create Community V1

### ISSUE THREAD

**Issue by kurtisassad** [hicommonwealth/commonwealth#5795]
## Description
Certain changes on the backend need to be made to support the new Create Communities V1 design.

## Engineering Requirements
The following DB changes need to happen, and support for them needs to be added to create_community.ts.
- [x] remove default_symbol from Communities #5780
- [x] add support for arbitrary social links for communities. This will also require the db migration to migrate old social links #5815
- ~[ ] add dao and defi boolean columns to Communities table.~
- [ ] ~add community namespace field to Communities table~
- [x] Refactor create_community error handling to zod. Create fields mentioned above to unblock front-backend integration. #5799
- https://github.com/hicommonwealth/commonwealth/issues/6004
- https://github.com/hicommonwealth/commonwealth/issues/6006
- https://github.com/hicommonwealth/commonwealth/issues/6009

**Comment by jnaviask** [comment]
@kurtisassad what do you mean by arbitrary links?

Also, re "dao" and "defi", those are currently already defined as an array under the `categories` column on `Communities`.

**Comment by kurtisassad** [comment]
Social links, updated ticket accordingly.
