### ISSUE TITLE
🪣 Improved notifications system & push notifications (Backend)

### ISSUE THREAD

**Issue by timolegros** [hicommonwealth/commonwealth#6730]
## Description

This ticket encompasses all of the platform and integration work required to implement the improved notifications system V1 (including push notifications).

Per the analysis + discussion on https://github.com/hicommonwealth/commonwealth/issues/6545, we will proceed with Courier as our external notifications provider (pending the prototype to validate this decision).

The [Mero board for notifications](https://miro.com/app/board/uXjVNZ8oB3U=/?moveToWidget=3458764569080472490&cot=14) outlines the story/flow for each notification and for the system as a whole.

The [flow-state diagram](https://www.figma.com/file/VRD0Z72rRiQhcGnq8P21Vj/Notifications-diagram?type=whiteboard&node-id=0%3A1&t=vVz8Q9h3EdDQuCGY-1) dictates when notifications should be emitted (based on user preferences).

### Architectural Diagram
![NotificationsImprovement-2](https://github.com/hicommonwealth/commonwealth/assets/62490329/4b2f8dbe-d957-4f9c-b764-2a731850bd23)

### Tasks
There are three main sections of work (to be done in order):
- [x] 1. Prototype: https://github.com/hicommonwealth/commonwealth/issues/6742
To validate Courier and our architectural decisions we need to build a prototype. This prototype should bypass the transactional outbox pattern and focus solely on emitting a single thread creation event for a small sample of test users. The prototype must include building a Courier workflow that emits to channels we currently support i.e. email and in-app. It should help us familiarize ourselves with the various Courier APIs and workflow building.

- [x] Platform: https://github.com/hicommonwealth/commonwealth/issues/6738
The platform work consists of creating a proper structure for emitting events via the [transaction outbox pattern](https://microservices.io/patterns/data/transactional-outbox.html).

- [x] Integration: https://github.com/hicommonwealth/commonwealth/issues/6740
The integration work involves setting up the proper RabbitMQ queues and the Courier consumer to handle the various types of events that land in the outbox. It also involves setting up all of the appropriate workflows in Courier (Courier configuration).

## Project Owner

@timolegros @Rotorsoft

**Comment by jnaviask** [comment]
Took a quick review: this is really good -- is marking notifications as read in scope?

**Comment by timolegros** [comment]
> Took a quick review: this is really good -- is marking notifications as read in scope?

Marking notifications as read will be done directly from the client with the Courier SDK (might even be auto-managed with Courier ReactJS SDK hooks but not sure). This will be completed as part of a new client ticket that is yet to be created (child of https://github.com/hicommonwealth/commonwealth/issues/6617)

**Comment by jnaviask** [comment]
Notes from 2/20/24 kickoff call:

#6742 -- est 1 week
#6738 -- est 2 weeks
#6740 -- est 1.5 weeks
total: ~4.5 wk of engineering work not incl QA => round up to 5 weeks full buildout

Expected wins on completion:
1. Courier workflows => allows us to attach new notification destinations without code changes
2. Improved decoupling of application => streaming core domain events; foundational work
3. Massively improved scalability + robustness => can drop Notifications[Read] table, reactive framework handles failures => would be interested in quantitative description of improvement
