### ISSUE TITLE
🪣 Referrals V1

### ISSUE THREAD

**Issue by HIM92** [hicommonwealth/commonwealth#7766]
### Description

The referral project encompasses the the experience of the referrer (person sending the invite) as well as the referral (person receiving it). 

There are two sides of this project that will be merged at launch. The first section of this is the Web 2 best practices informed by successful Web 3 businesses (Binance, Zora, EthenaFi). There are a few functions that are key here to achieve the share ability we're looking for. 

- Anyone can become a referrer
- You can refer to either common as a platform, or a direct community
- messaging app compatability
- incentives for the user to become a referrer
- incentives to join via referral. 

The second section of the project is on the protocol side, where the the referrer receives a portion of any fees generated by his/her referrals. 

- Contract fee manager provides the fee split between common and the referrer
- Incentive for the referral to sign up (fee discount / NFT -> TBD)

The project cannot be launched without both sides being complete, otherwise it will be uninteresting to the uer. 

### Project Owner

@Him9289

### PRD

https://docs.google.com/document/d/1YnU96E7UNMLhRTtlfiolsie_2VVlJXn7S8s6SyqxBRg/edit#heading=h.aznt4szbo6c9

### Tasks

- [x] https://github.com/hicommonwealth/commonwealth/issues/7770
- [x] https://github.com/hicommonwealth/commonwealth/issues/7771
- [x] #10035
- [x]  #10141
- [x] https://github.com/hicommonwealth/commonwealth/issues/7772
- [x] https://github.com/hicommonwealth/commonwealth/issues/7775
- [x] #10063
- [x] https://github.com/hicommonwealth/commonwealth/issues/7777
- [ ] https://github.com/hicommonwealth/commonwealth/issues/7767

Protocol Side:
- [x] https://github.com/hicommonwealth/commonwealth/issues/7783

Platform Side:
- [x] #9832 
- [x] #10492
- [x] #10494
- [x] #10542
- [x] #10581

### Design Links

https://www.figma.com/file/Vr3dv2IjUFSonyxZdwzfVU/Referral-Program?type=design&node-id=234-4556&mode=design&t=Z5OYcCvlgm7bEOCM-0

### Additional Context

referral behavior and protocol flow: https://www.figma.com/file/FcVnthOnUoFC5kXzJLyDNG/Flow-of-funds%2C-referral?type=whiteboard&node-id=7-335&t=r65rAjLFfp86S8OH-0

[Link to Github](https://github.com/hicommonwealth/common-protocol/blob/main/src/Referral/ReferralFeeManager.sol)
```
/**
 * @title ReferralFeeManager
 * @dev This contract manages referral fees for a namespace system.
 *
 * Key features:
 * 1. Allows setting referrals for namespaces
 * 2. Manages fee distribution between referrals and a protocol fee destination
 * 3. Supports both ETH and ERC20 token fee distributions
 * 4. Implements role-based access control for various functions
 *
 * Roles:
 * - NAMESPACE_FACTORY_ROLE: Can set referrals for namespaces
 * - FEE_DISTRIBUTOR_ROLE: Can trigger fee distribution
 * - OWNER_ROLE: Can update fee split percentages and protocol fee destination
 *
 * The contract allows for flexible fee distribution, where fees can be split
 * between referrals and a protocol fee destination based on a configurable
 * percentage. If no referral is set for a namespace, all fees go to the
 * protocol fee destination.
 */
contract ReferralFeeManager is AccessControl {
    using Address for address payable;
    using SafeERC20 for IERC20;

    // Role for the namespace factory contract, allowed to set referrals for namespaces
    bytes32 public constant NAMESPACE_FACTORY_ROLE = keccak256("NAMESPACE_FACTORY_ROLE");

    // Role for addresses allowed to trigger fee distribution
    bytes32 public constant FEE_DISTRIBUTOR_ROLE = keccak256("FEE_DISTRIBUTOR_ROLE");

    // Role for the contract owner, allowed to update fee split percentages and protocol fee destination
    bytes32 public constant OWNER_ROLE = keccak256("OWNER_ROLE");

    // Maps namespace addresses to their corresponding referral addresses
    // If a namespace has no referral set, the mapping will return the zero address
    mapping(address => address) public namespaceToReferral;
    
    // Percentage of fees that go to the referral (0-100)
    // The remaining percentage (100 - feeSplitPercentage) goes to the protocol fee destination
    uint256 public feeSplitPercentage;

    // Address where the protocol's share of the fees will be sent
    // This is used when there's no referral set or for the protocol's portion of split fees
    address public protocolFeeDestination;

    event ReferralSet(address indexed namespace, address indexed referral);
    event FeeSplitUpdated(uint256 newSplitPercentage);
    event ProtocolFeeDestinationUpdated(address newDestination);
    event FeesDistributed(address indexed namespace, address indexed token, uint256 amount, address recipient, uint256 recipientAmount);
    event FeeDistributorAdded(address indexed newDistributor);
```

**Comment by dillchen** [comment]
@timolegros and @Rotorsoft  tagging u here as platform side owners, to add the Platform tickets
