### ISSUE TITLE
🪣 Thread IA: Sidebar revamp

### ISSUE THREAD

**Issue by HIM92** [hicommonwealth/commonwealth#7986]
### Description

The goal of this project is to enhance the navigability and usability of the user sidebar for all users, including members and admins. Previously, the sidebar lacked clarity regarding which addresses were activated in the communities to which users belonged. It also did not offer personalization or account visibility and failed to consistently represent notifications visually. This project aims to address these issues in its first stage, focusing on improving the sidebar's navigability and visibility.

### Project Owner

@HIM92

### PRD

https://www.notion.so/buildcommon/Editor-Threads-V2-1718fd6b8fdd460291a43453a15e6012?pvs=26&qid=

### Tasks

- [x] https://github.com/hicommonwealth/commonwealth/issues/7987
- [x] https://github.com/hicommonwealth/commonwealth/issues/7988
- [x] https://github.com/hicommonwealth/commonwealth/issues/7989
- [x] https://github.com/hicommonwealth/commonwealth/issues/7991
- [x] #10426
- [ ] ~~Remove "addresses from the top nav drop down"~~

### Design Links

https://www.figma.com/design/irjQpCSI3Tv15e3JnYCnR5/Thread-IA?node-id=2157-3031&t=TRlBJsssdvVuVYT5-0

### Design Screenshots

<img width="1158" alt="Screenshot 2024-05-30 at 12 18 00 PM" src="https://github.com/hicommonwealth/commonwealth/assets/153562904/8c056989-0284-445f-b132-527770f1c7d5">
<img width="382" alt="Screenshot 2024-05-30 at 12 19 32 PM" src="https://github.com/hicommonwealth/commonwealth/assets/153562904/188be0bb-59f5-4a47-aafe-fbb92b4ca5f3">
<img width="598" alt="Screenshot 2024-05-30 at 12 43 17 PM" src="https://github.com/hicommonwealth/commonwealth/assets/153562904/245a10fc-2b1f-4c3a-9a3a-749ced13ea64">
<img width="204" alt="Screenshot 2024-05-30 at 12 54 24 PM" src="https://github.com/hicommonwealth/commonwealth/assets/153562904/00fb7d67-3e86-4bb7-9380-7f4a9630c803">
<img width="206" alt="Screenshot 2024-05-30 at 12 56 42 PM" src="https://github.com/hicommonwealth/commonwealth/assets/153562904/b9c9c3aa-b8c1-43d0-9958-2ad02fa3465d">

### Additional Context

https://www.loom.com/share/2717d036e2e34ac9b7495cf154b0c795?sid=c7e7e126-303c-4976-8030-01eebf0ec698
