### ISSUE TITLE
🪣 Fix frontend type issues around tRPC

### ISSUE THREAD

**Issue by burtonator** [hicommonwealth/commonwealth#8033]
### Description

We still have some tRPC issues that will cause issues on the client.  Most of these are deal breakers for moving forward everywhere with tRPC so I created a list of tickets we should fix.  

### Project Owner

@burtonator

### PRD

These are broken down into the tasks.

### Tasks

- [ ] https://github.com/hicommonwealth/commonwealth/issues/7996
- [ ] https://github.com/hicommonwealth/commonwealth/issues/7983
- [ ] https://github.com/hicommonwealth/commonwealth/issues/7890
- [ ] https://github.com/hicommonwealth/commonwealth/issues/7866
