### ISSUE TITLE
Set up K6 Cloud Integration + Heroku App

### ISSUE THREAD

**Issue by timolegros** [hicommonwealth/commonwealth#8064]
## Tasks
- [x] Create a K6 Cloud account with `infra@common.xyz` email
- [x] Get environment variables from K6 and update the local configs (requires PR)
- [ ] ~~Set up Prometheus (if possible/necessary) on the cloud env~~
- [ ] ~~Set up Graphana on K6~~
- [ ] ~~Create a Heroku app with a setup near identical to production (if DB/dyno's are smaller than load test should be scaled down accordingly)~~

**Comment by timolegros** [comment]
I don't think we should collect Postgres metrics in k6 cloud since it would continually be active and therefore costly. Additionally, I don't think we need a separate Heroku app (replicated from prod) for load testing since we can establish baseline load-test metrics on smaller server instances and occasionally scale to prod instances to determine maximum load.
