### ISSUE TITLE
🪣 Relaunch Topic Templates

### ISSUE THREAD

**Issue by HIM92** [hicommonwealth/commonwealth#8090]
### Description

When creating/editing a Topic for my community, an admin (optionally) might want to encourage posts to follow a particular format or include particular information. Introducing, Topic Templates: prewritten (by admins) Markdown Text that auto-populates into the New Thread Body Editor when the topic is selected. The community member will have the option to edit or delete the auto-populated text as they see fit. If the community member has already begun writing in the New Thread Body Editor, the Topic template does not override their existing text. 

### Project Owner

@HIM9289

### PRD

https://www.notion.so/buildcommon/Topic-Templates-9b8a07ede6e6422db2ed397033e64e69

### Tasks

- [x] https://github.com/hicommonwealth/commonwealth/issues/8091
- [x] https://github.com/hicommonwealth/commonwealth/issues/8092
- [x] https://github.com/hicommonwealth/commonwealth/issues/8093

### Design Links

https://www.figma.com/design/KuifrBhTzPi7Tt9dpfUelB/Topics-%2B-Subtopics---V1?node-id=585-4537&t=i9KuLbycmBVASp1S-0

### Additional Context

- Only admins can create or edit topics and topic templates

**Comment by ForestMars** [comment]
@mzparacha As with Address Management, can you please estimate the overall bucket here? (total points)

**Comment by KaleemNeslit** [comment]
@dillchen  i need access to figma and maybe for notion as well
