### ISSUE TITLE
🪣 SEO changes for switching our domain and targeting 10x SEO

### ISSUE THREAD

**Issue by burtonator** [hicommonwealth/commonwealth#8395]
### Description

We could possibly 10x our search traffic and I document that here:

https://github.com/hicommonwealth/commonwealth/issues/8389

We should make the following changes to implement this.

- [ ] https://github.com/hicommonwealth/commonwealth/issues/8392
- [ ] https://github.com/hicommonwealth/commonwealth/issues/8386
- [ ] https://github.com/hicommonwealth/commonwealth/issues/8385

It's going to take from 2-4 weeks to see these changes implemented, rolled out, and Google updated.

### Project Owner

@burtonator

### PRD

none

### Tasks

- [ ] https://github.com/hicommonwealth/commonwealth/issues/8392
- [ ] https://github.com/hicommonwealth/commonwealth/issues/8386
- [ ] https://github.com/hicommonwealth/commonwealth/issues/8385
