### ISSUE TITLE
🪣 Develop External API

### ISSUE THREAD

**Issue by Rotorsoft** [hicommonwealth/commonwealth#8694]
### Description

We need to develop an external API that can be exposed to a set of customers through an API gateway. The initial phase will support a limited number of queries to access community content (threads and comments). This ticket outlines the functional and technical requirements for implementing this.

## Phase 1 Objectives
- Define subset of API queries for reading threads, comments and reactions. 
- Ensure secure and controlled access
- Provide logging and monitoring

## Functional Requirements
- [x] Expose selected endpoints of the internal API to customers (TBD by product team)
- [ ] Ensure endpoints are clearly documented and accessible
- [ ] Implement authentication mechanisms to ensure only authorized users can access the API (API key or token-based authentication)

## Technical Requirements
- [ ] Proxy Configuration
  - [ ] Set up proxy rules to route incoming requests to the internal API
  - [ ] Ensure proper handling of request and response headers
- [ ] Authentication
  - [ ] Support for API key or JWT authentication
  - [ ] Integrate with an existing identity provider for user management (Canvas)
- [ ] Rate Limiting
  - [ ] Define and configure rate limits (e.g., requests per minute/hour)
  - [ ] Define strategy (by user tiers, by credentials, by ip, etc)
- [ ] Logging
  - [ ] Enable detailed logging of all incoming requests and outgoing responses
  - [ ] Store logs in a centralized logging system for analysis
- [ ] Monitoring
  - [ ] Implement real-time monitoring and alerting for API usage
  - [ ] Tools to visualize API performance metrics and detect anomalies

### Options for API Gateway

- [x] Choosing existing infrastructure until a more sophisticated gateway is necessary

#### Use existing infrastructure
- Configure Cloudflare to rate limit requests (by ip or credentials)
- Rely on Heroku load balancing

#### KrakenD
- Pros:
  - Open source, self hosted
  - High performance and low latency
  - Declarative configuration
  - Support for complex routing and transformations
- Cons:
  - Less mature ecosystem compared to Kong
  - Requires more manual setup for certain features
   
#### Kong
- Pros:
  - Mature and widely adopted ecosystem
  - Rich plugin ecosystem for additional functionalities
  - Easy integration with various authentication and monitoring systems
- Cons:
  - Slightly higher overhead compared to KrakenD
  - Price

## Acceptance Criteria
1. External API endpoints are accessible through the gateway
2. Authentication is implemented and enforced
3. Rate limiting is applied and functional
4. Logging and monitoring are enabled and providing insights

### Project Owner

@rotorsoft

### PRD

[API Sequencing](https://www.notion.so/buildcommon/API-Sequencing-a1fb520348de4d5b82fc6c679e8b29c6)

#### Phase 1: Routing and MVP queries
- [x] #8782
- [x] #8783
- [x] #8838
- [x] #8867
- [x] #8890

#### Phase 2: Authentication utils and MVP mutations
- [x] #8874
- [x] #8875
- [x] #8905
- [x] #8876
- [x] #8878
- [x] #9204

#### Phase 3: Finish infrastructure and route refactoring
- [x] #9470

 

### Additional Context
[API Launch Sequence](https://docs.google.com/document/d/1qtgpFmYBmlh48qrmcfIFjqA7NgXedjjr2lwqm13iEgw/edit)
[API Requirements](https://docs.google.com/document/d/1o7AxTqrdiMHovT10-MKWtG0PMMAXgP2Fy7h20EgscWE/edit#heading=h.6mhzqr455f0m)

#### KrakenD
![image](https://github.com/user-attachments/assets/5b09bfd8-6bc3-4f74-ba46-c7209feb1498)

_No response_

**Comment by timolegros** [comment]
I would say that self-hosting an API gateway is a con, not a pro. While it would technically be cheaper we have limited manpower to maintain self-hosted services.

**Comment by Rotorsoft** [comment]
> I would say that self-hosting an API gateway is a con, not a pro. While it could technically be cheaper (maybe not considering eng hours) we have limited manpower to maintain self-hosted services.

yes, it could be considered a cons if we determine that dev and maintenance costs are higher

**Comment by raykyri** [comment]
Outlined the Canvas Identity Provider here, including a auth flow diagram, explanations of how self-custodial identity works, and some code examples: https://github.com/canvasxyz/canvas/blob/main/IDP.md#client-identity-format

There are some TODOs left later in the document around how to pass around serialized Sessions/Actions. Basically just defining some standard formats for using them as bearer tokens.

**Comment by dillchen** [comment]
I do want to chime in, we've set up Kong In the past

**Comment by Rotorsoft** [comment]
> I do want to chime in, we've set up Kong specifically in the past

Yep, Kong should be the winner... adding KrakenD just to have a second option.

**Comment by raykyri** [comment]
For Canvas or Common? There is one for Canvas further up the page, lmk if there are any details worth adding

**Comment by Rotorsoft** [comment]
We discussed the public API issue in detail during our weekly retro and concluded that our current API is already somewhat public. We just need to ensure that the front "gateway" layer rate limits users to prevent attacks. Since we are not charging for API usage, there is no need to rate limit for quotas, so a basic Cloudflare config would do.

We also considered having Canvas provide a Passport strategy to authenticate addresses as a new authentication option. However, we can currently expose the existing tRPC API to users by generating TypeScript client proxies from the OpenAPI specs. This will be simpler than maintaining a RESTful API and extra documentation.

Decided actions for the next steps:
1. Embed the `address_id` of the authenticated user in the JWT instead of passing it in the headers. This will better encapsulate identity and avoid the need to revalidate addresses in the middleware.
2. Generate a TypeScript client proxy from the existing OpenAPI specs to simulate an external user flow. We will write a small Node.js app for this purpose.
3. Make sure our existing infrastructure provides proper rate limiting functionality at the user level (might need to decode JWT to rate limit by address_id)

**Comment by raykyri** [comment]
If it's possible to expose the existing tRPC API that saves a lot of work and will definitely be much more maintainable. It's worth considering how we want to think about self-certifying data from API consumers/bots - it would not be too difficult to add the ability to sign over actions from external API consumers for example.

**Comment by dillchen** [comment]
Raymond, could you say more here.

I think it seems good that we are converging on simplicity.

Sent via Superhuman iOS ***@***.***>

**Comment by raykyri** [comment]
Some progress on this in advance of today's call:

* Roger gave me a short run through of passport auth and how he determined we should implement an auth strategy for the external API going forward.
* I looked at passport auth strategies, and determined that implementing one for either address_id or Canvas session/action objects is feasible and within the range of our estimates. That ticket is assigned to me now.
* Will still reserve the call for general alignment questions, especially those about API and federation.

**Comment by timolegros** [comment]
https://github.com/hicommonwealth/commonwealth/issues/9378 this should be a follow-up or part of the later phases.

**Comment by dillchen** [comment]
Good to close this ticket?

**Comment by Rotorsoft** [comment]
> Good to close this ticket?

Not yet, we have to finish a couple of tasks in phase one and two. We can postpone phase 3 though

**Comment by Rotorsoft** [comment]
All tickets closed
