### ISSUE TITLE
🪣 Deploy Stake + Contests on 3 Chains (Phase 1 of Decoupling)

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#8695]
### Description

For simplicity's sake, we'd like to deploy Stake + Contests on 3 Alchemy supported chains, enabling our Admins for launching Stake+Contests on different chains. The below chains are ordered by impact:
- Linea (Growth Request, a DAO on Linea wants to experiment with Contests, good test community)
- Optimism (Many new DAOs popping up here, a market we'd like to sell to)
- Eth Mainnet (Incumbent market, but highest cost to use)

Ultimately, we want to decouple Stake + Contests, however, that is out of scope for this immediate project making available these features to more communities. 

### Project Owner

Sachin Benny, Zak Hap @zakhap

### PRD

The Larger Decoupling Project Overview is here: https://www.notion.so/buildcommon/Decoupling-dbb7fdf225654190b111210b73e60384

This Bucket is a precursor bucket ticket to all of the work described in the document.

Enable Stake + Contests on: 
- Linea
- Optimism Mainnet
- Ethereum Mainnet
- Added on **8/12/24**: BNB see msg ([link](https://github.com/hicommonwealth/commonwealth/issues/8695#issuecomment-2284778804))
- Arbitrum
### Tasks

- [x] https://github.com/hicommonwealth/common-protocol/issues/163
- [x] https://github.com/hicommonwealth/common-protocol/issues/164
- [x] https://github.com/hicommonwealth/common-protocol/issues/165
- [x] #8970
- [x] #8971

**Comment by timolegros** [comment]
I have shared this a few times but will add here for context as well: https://github.com/hicommonwealth/commonwealth/blob/master/knowledge_base/Chain-Feature-Matrix.md. This is the current chain feature matrix. If Linea is seriously to be considered we _really_ need to evaluate how critical it is compared to the eng effort lest we fall back to our previous model of 'supporting any chain anytime at any cost'. The previous model was very expensive to maintain and should be avoided.

Per @ianrowan's comment, contests on ETH mainnet seem completely unsustainable but that's outside my purview.

**Comment by dillchen** [comment]
Mark has added context here:

https://www.notion.so/buildcommon/Growth-Chain-Priority-Docs-a4c66f8238a546d8b5e49ecaa67b2c01?pvs=4

The other requested chains is BNB. cc: @timolegros

**Comment by jnaviask** [comment]
Backlogging until we reach a final decision.

**Comment by dillchen** [comment]
What needs final decision?

Who do you need final decision from?

Sent via Superhuman iOS ***@***.***>

**Comment by ianrowan** [comment]
To begin planning for this, wanted to provide the expected tasks here which can be ticketed upon acceptance. 

1. Security set-up for each network 
    - Creation of all 7(?? @egetekiner ) multi-sigs per network. Is safe available on all networks? 
    - Funding of all key holder accounts on all networks(35 addresses per network i believe)
2. Deployment of Contracts per chain
    - Consolidated full deployment script required(ie Namespace + contests) 
    - Funding of deployment key per network 
    - potential key holder coordination for txs 
3. Protocol updates to CW app
    - add addresses to `chainConfig` for each new network 
4. Platform configurations 
    - Adding alchemy webhooks/CE for each network/contracts CC @timolegros on this
5. Final configurations 
    - Any app deployment plan steps to spin this up
    - Funding and monitoring for Contest sequencer on each network

**Comment by egetekiner** [comment]
We can setup the deployments for Monday Aug 26th and we can use the same keys for the multisig creations. Only thing we need to do is to fund all of the wallets in the networks we would like to deploy. 

If that's ok for everyone, I can start to create multisignature wallets and once all of them will be ready we can come together for the deployment (or only @ianrowan and I can take care of it).

**Comment by ianrowan** [comment]
I've added tickets to track these tasks to the task section of this bucket. Would say to be accurate the deployment portion of these tickets will start on Aug 26th but may run into the next day or two given the light dev work/testing potentially required. 

The platform side tickets may be more involved but pinged team members to weigh in on effort on those. 

CC @jnaviask

**Comment by ianrowan** [comment]
Confirmed #9108 will be added as a hotfix from team 

CC @ilijabojanovic
