### ISSUE TITLE
🪣 Launchpad and community create

### ISSUE THREAD

**Issue by HIM92** [hicommonwealth/commonwealth#8703]
### Description

Launchpad is an integration with work already executed by Ege and Ian on the protocol team allowing users to create and launch an ERC20 token on the Base blockchain. This milestone provides the tickets for that basic functionality whereby a user can launch a token, and a community for their token. 

As part of this, any other user of Common, whether they are a member of the  community or not, can purchase the token. They can do this within the community, and eventually as part of the discover and explore page. 

The market cap is set to a bonding curve and increases quadratically with each purchase, and decreases with each sale. When the market cap hits [$10,000], it is deployed to a uniswap pool where it can be freely accessed on their platform or by any trading bots directly on uniswap. 

The functionality of this milestone relates to launching the token, naming and creating the community that supports it, and then the functionality of the progress bar, and the buying and selling functions. 

List:

- [ ] Token launching
- [ ] Detailed requirements for the token
- [ ] Create a community for the token
- [ ] Sign to launch the token
- [ ] Transaction modal
- [ ] Buy and sell
- [ ] Market Cap progress bar

### Project Owner

HIM92

### PRD

https://docs.google.com/document/d/1VtJI8sb4LhBjBk6g07JqLtzBnCBfPzQZ3rkXFSjsrhU/edit?pli=1#heading=h.lraxrsoqvryu

### Tasks
- [x] Add feature flag (not ticketed) 
- [x] https://github.com/hicommonwealth/commonwealth/issues/8704
- [x] https://github.com/hicommonwealth/commonwealth/issues/8705
- [x] https://github.com/hicommonwealth/commonwealth/issues/9207
- [x] https://github.com/hicommonwealth/commonwealth/issues/8706
- [x] https://github.com/hicommonwealth/commonwealth/issues/9208
- [x] https://github.com/hicommonwealth/commonwealth/issues/8707
- [x] https://github.com/hicommonwealth/commonwealth/issues/9321
- [x] https://github.com/hicommonwealth/commonwealth/issues/9371
- [x] https://github.com/hicommonwealth/commonwealth/issues/9370

### Design Links

https://www.figma.com/design/1b9wbqv9YV2FlU2svFyf0I/IdeaCoin?node-id=815-39215&t=CPzA8TQX48r6yzZy-0
