### ISSUE TITLE
🪣 Migration plan for a real CI/CD pipeline.

### ISSUE THREAD

**Issue by burtonator** [hicommonwealth/commonwealth#8717]
### Description

I'd like to migrate us to a CI/CD release where:

- we have more test coverage but also *critical* test coverage so that it's difficult to impossible to push a broken release
- all merges to master are automatically released

The main goal is to improve our release cadence.

The goal is to increase the rate we push code, help us get to PMF faster, and also make development a more reliable and enjoyable process.

This is going to take a while though. I don't expect this to happen overnight and we'll probably have to migrate over 2-6 months.

We can clean up a lot of these issues during Friday cleanup days.

The main tasks we need to improve are:

### Project Owner

@burtonator

### PRD

none for now... just this document.

### Tasks

- [ ] Get team buy-in and approval that this is our long term goal
- [ ] Figure out the core/critical tests we need to verify build validity before deploy
- [ ] https://github.com/hicommonwealth/commonwealth/issues/8716
- [ ] Implement the changes to automatically push master on every commit
- [ ] Implement a frontend test framework
- [ ] Agree that all *new* PRs must have test coverage and agree on a process

**Comment by burtonator** [comment]
@timolegros had this note in another PR:

> One concern I have for frequent deployments is that Heroku deployments are not seamless. When we deploy Heroku dynos restart leading to 10-30 seconds of downtime. If we release on every master merge this could lead to several minutes of downtime per day which may be undesirable. Not sure what we can do about this other than maybe deploy to master on a set schedule during low-traffic hours e.g. every day at X time.

I'll create issues for all the above but we might have to fix this first.

**Comment by burtonator** [comment]
Talked to @timolegros about this and we could use 9AM scheduled releases in Heroku.
