### ISSUE TITLE
🪣 Canvas part 2

### ISSUE THREAD

**Issue by ForestMars** [hicommonwealth/commonwealth#8726]
### Description

Bucket ticket for Canvas API work (NB. separate from other Canvas milestone) 

### PRD

https://www.notion.so/buildcommon/Common-Protocol-Ecosystem-Canvas-Deliverable-2-d5a07b619e6b4f239b18f9062bf8b4e0

### Tasks
- [ ] Raymond will groom (this) bucket ticket.
- [ ] Dependency on write threads API? 
- [ ] Finalize and expose API for roles & groups 
- [ ] Create Community dependency 

- Load balancing using heroku
- Define a logical layer for handling rate limiting, load balancing, auth api keys and requests
- Use signed data (sessions) and a directory service as API consumer credential

## Open Questions
- [ ]  How to reconcile internal R&P models (1 sys level → community level → group permissions (gating) with new API model)
- [ ] How to make decision around common api service? (separate out content api?) 
- [ ] (Assuming gateway) design? 
- [ ] Decision on load balancing -> start with Heroku dyno (not Kong or other ext GW)
- [ ] What is interface surface/shape (on Canvas side)
