### ISSUE TITLE
Spike to test Lexical as our editor!

### ISSUE THREAD

**Issue by burtonator** [hicommonwealth/commonwealth#8751]
## Describe the bug

I need to get a spike to test using Lexical as our editor with markdown.  

### Implementation Notes

- internally they have a 'shared' package in their monorepo that I think I'm going to have to republish because their 'playground' implementation is pretty robust but uses code from 'shared' but it's a private NPM repo.

### TODO (v0)

- [x] Load markdown from raw markdown data
- [x] Figure out how to export markdown
- [ ] The hover bar that pops up when you select text just stopped working
- [x] test out dark mode
- [ ] test out mobile toolbar.
- [ ] Test out all our markdown options including GFM including import and export
- [x] Research async image uploading and blob image handling from the paste buffer

#### What's broken
- Tables are broken.  Both input and output.  Only DOM manipulation works.
- sub and sup scripts aren't working when converting to markdown.  
- <hr> doesn't work for markdown dump

### TODO (v1)

- [ ] Implement async image loading

### Advanced

- [ ] Should we talk to the team about auto-embedding
- [ ] What do we do for "at" mentions and hashcodes?

### Takeaways

- there is no default async image uploading when pasting.  We will have to take the blob and then put the editor into an 'uploading' state, then upload the image, then rewrite the markdown.  We should use a blob or a data URL in the mean time.  We probably need a CANCEL state while it's uploading

### Initial conditions

**Environment:** 

**Branch/Release version:** 

**Browser:** 

**Wallet:**

**Comment by burtonator** [comment]
Finished enough work for a v0 spike.... I'm going to have to research next how hard it's going to be to implement proper markdown as their 'playground' doesn't have this implemented properly.

**Comment by burtonator** [comment]
This one is done.  I've decided to try with MDXEditor as Lexical will be too much of a pain unfortunately.
