### ISSUE TITLE
🪣 Referrals - Protocol Contracts

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#8857]
### Overall (added by Dillon)

We want our users to invite other users to join Common, invest in their communities, and participate in contests. Therefore, we should build a referral system that encourages and rewards this behavior. Offchain, we want users to be able to deploy referral codes to their preferred channels (twitter, discord, telegram) easily, without too many clicks. The referrer should be rewarded for each action that the referral takes both financially and with platform specific points. 

### Description

This ticket is the onchain component for referrals. 

There are 3 sources of potential fees:

- when `referree` creates a namespace, FeeManager, Contest, or Stake Contract. `referrer` should gets fees for any transactions that get created inside the `referree`
- when `referree` creates a transaction to BuyStake, SellStake, and later BuyLaunchpadCoin and SellLaunchpadCoin. `referrer` should get fees here for each transaction.
- when `referree` wins any money from a contest `referrer` should get a portion of fees here.

For each of these, the `referree`'s address should be added as an additional fee destination. This means that any onchain action within those contracts should be directed to the  `referrer` as well as the protocol (us).

The `referrer`'s fee split should be take directly and only from the `protocolFee` split. We currently expect 33% of the `protocolFee` to be split to the `referrer`.

If we implement this referral system, we expect to see increased user acquisition and transaction volume, leading to higher protocol fees and broader adoption of our platform.

**Success Metrics**
- Number of new namespaces created through referrals
- Percentage increase in overall namespace creations
- Volume of transactions referred by developers
- Increase in protocol fees generated
- User satisfaction and engagement rates

**NonGoals**
- Implementing a points system
- Creating multi-level (two-layer) referrals
- User-configurable bounties (reserved for Protocol Engineering)

### Project Owner

@dillchen, @zakhap

### PRD

https://www.notion.so/buildcommon/User-Configurable-Referrals-Protocol-Eng-Only-b276780020324471904479e4c45aae84

### Tasks

- [ ] When `referree` signs up with an invite link
   - Store the referrer's address to the DB
- [ ]  In Stake Contract, When user creates Buy / Sell Stake
    - Use the platform-side stored `referrer`'s address
    - Update protocol calls to include tx_referrer parameter (following Zora pattern)
- [ ]  In StakeFactory Contract, when contract gets created
    - Use the platform-side stored `referrer`'s address
    - Update protocol calls to update fee destination to include `referrer`'s address
    
- [ ]  In Launchpad Contract, when contract gets created
    - Use the platform-side stored `referrer`'s address
    - Update protocol calls to update fee destination to include `referrer`'s address for any non Buy / Sell Fees
- [ ]  In Launchpad Contract, When user creates a Buy / Sell Coins
    - Use the platform-side stored `referrer`'s address
    - Update protocol calls to update fee destination to include `referrer`'s address
    
- [ ] In Namespace Contract, Implement Namespace Creation Referrals
    - (Optional) Add referral code input to the UI for namespace creation
    - Update Protocol Fee destination for Stake/Contests to include `referrer`'s address
    
- [ ] In Contest Contract, Implement fee winner split
    - when `referree` wins any money from a contest `referrer` should get a portion of fees here.
    - Create mapping of community => create_referrer

Outside the Scope at the moment: 
- Creating the Admin UI
- Monitoring and Analytics
- Deployment and Launch
- Documentation and Training for Growth Team

### Design Links

NA

### Design Screenshots

NA

### Additional Context

- [Flow of Funds](https://www.figma.com/file/FcVnthOnUoFC5kXzJLyDNG/Flow-of-funds%2C-referral?type=whiteboard&node-id=0-1&t=QvDkqRxWQFIVRyv6-0)

**Comment by ianrowan** [comment]
A few questions. 

1. Can we clarify the exact source of funds that should be split 33%(variable) to the referrer? For context the naming conventions in the protocol currently are `protocol fee` = fee that goes direct to us and `namespace fee` = fee sent to the feeManager that then is sent to feeManager beneficiaries(ie contests). This ticket mentions protocol fees but I am assuming we mean namespace fees. If this is not the case I would recommend we different naming than `feeManager` as this is a concept directly tied to namespace fees at the protocol level.

2. Do we have any plans to require a referrer(ie technically invite only), given namespace creation is client driven and this ticket mentions it being user input - what incentivizes a user to use their invite code if it results in giving up 33% of their fees? 

3. When considering the use of invite codes do we expect to have platform side functionality to convert an invite code to a referrer address and then autofill that in the namespace creation transaction? Or are we expecting to have some sort of onc-chain mapping of invite codes to addresses(not recommended)  

4. How does a user/address become eligible as a referrer, ie how does the user get an invite code(if we go that direction)? How do we guard against the light-exploit of always being able add another wallet a user holds as an referrer so that they can reduce fees by 33% for example? Note this gets tricky to defend against on-chain in the case where a user can rig the transaction regardless of invite code to include their address in the referrer input field.

In summary, the main item that is still an open question for me is less on the protocol(on-chain) side of things here but rather the platform considerations to support a less exploitable referral system. Most of this is difficult to defend against at the on-chain level so I might suggest more research into how general referral systems implement this with invite codes to reduce abuse of the system.

I would suspect the platform would need to implement some logic that validates invite codes and at least uses our profile/connected address relations to defend against the note exploit. This adds slight complexity to the on-chain implementation as this would expect the platform to act as an oracle, providing a signature to send along with the tx that validates addition of the referrer. If we go this route non-referrer namespace creation can still remain permissionless most likely 

CC @jnaviask @egetekiner

**Comment by ianrowan** [comment]
Would also like to note that the above complexity can be bypassed/ignored if a product/business decision such as 'We aren't concerned with the sybil referrer exploit revenue loss' and we could proceed with simple referrer address input with optional invite code system on the platform side

**Comment by dillchen** [comment]
@ianrowan I've updated the ticket to better reflect the scope first based on your comment. All fees would be from the `protocolFee` split. I.e 33% of `protocolFee` goes to `referrer`.

This should handle question 1 and 2.

For number 3. We definitely will need to communicate and discuss this with the platform team. Mapping invite codes - to addresses. My TLDR would be in terms of onchain.

I do not have an answer for the 4th question here. My default answer here is that I am not as worried about sybil referrer revenue. per your last comment

**Comment by ianrowan** [comment]
Ok given the above an initial breakdown of how I would expect we implement this(ie the product spec for the protocol) is the following:

### ReferralFeeManager
- Create a new `ReferralFeeManager` contract
    - Contains mapping of namespace address -> referrer
    - Includes our vault address
    - variable fee split
    - callable fee distribution function to dump fee given a namespace address(or 100% to vault if none specified)
        - Note: this function will be expected to be called atomically with fee reception transactions as the contract has no way to be aware of the received balance of erc20 token so it will need tot always dump total balance. ie the contract should always be empty between transactions
- `ReferralFeeManager` becomes `protocolFeeDestination` in respective contracts 
- Upon Namespace deployment from factory(now including referrer field) `ReferralFeeManager.registerReferrer` function called by factory only to set up 

### Fee Distribution from protocol components
- This section will be where the most technical complexity arises due to (1) the constraint of the atomic function call to the above `referralFeeManager` when ever a fee is sent to the protocolFeeDestination (2) The existing parts of the protocol that are less composable in this aspect.
- For Contest Fee distribution we can use `claimHooks` to trigger fee dist(the interface is not ideal but possible)
   - Custom hook for `claimHook` that pulls contest data(contestToken, namespace, protocolFee dest) 
   - Hook calls dist function on `ReferrerFeeManager` post sending eth/erc20(the above items will likely be the interface)
- Launchpad would likely follow similar pattern to above and is more modular as its not deployed yet and hooks can adhere to requirements 
- Biggest challenge is stake, which currently does not have hooks for buy/sell. This means fees would be sent to `ReferralFeeManager` w/o a way to atomically distribute them.
    - May require a contract wrapper around the buy/sell functions on existing contracts to add hooks

**Comment by jnaviask** [comment]
@ianrowan once specification is accepted, please ticket the actual contract work and add to the Q3 Sprint board. I will then tag them accordingly.

**Comment by dillchen** [comment]
Will review

Sent via Superhuman ***@***.***>

**Comment by ianrowan** [comment]
Proposing the following tickets for this bucket if spec is accepted:

1. https://github.com/hicommonwealth/common-protocol/issues/159
2. https://github.com/hicommonwealth/common-protocol/issues/160
3. https://github.com/hicommonwealth/common-protocol/issues/161
4. https://github.com/hicommonwealth/common-protocol/issues/162

**Comment by dillchen** [comment]
I am good with this, let’s leave the Stake Wrapper till the end and
prioritize the RefFeeManager → Contest then others then Stake

Sent via Superhuman iOS ***@***.***>

**Comment by ianrowan** [comment]
@dillchen Sounds good will prioritize ticket (1) and (2) above and go from there
