### ISSUE TITLE
Use env var for Alchemy apps

### ISSUE THREAD

**Issue by timolegros** [hicommonwealth/commonwealth#9129]
## Description
Private Alchemy nodes now have centralized keys which we can store as `env` i.e. 1 key for all Alchemy supported chains.

## Tasks
- [ ] Remove all keys from ChainNodes
- [ ] Create new env var for each Alchemy App
- [ ] Create `ChainNodes.private_url` getters on the Sequelize model which append the Alchemy key if the url is an Alchemy endpoint.
