### ISSUE TITLE
Remove URI encoded titles and content from Threads

### ISSUE THREAD

**Issue by timolegros** [hicommonwealth/commonwealth#9168]
## Description
Thread titles are sometimes URI encoded and thread bodies are duplicated from the `body` column (encoded) into the `plaintext` (decoded) column.

## Tasks
- [ ] Decode all thread titles
- [ ] Ensure future saved titles are always decoded
- [ ] Decode thread bodies
- [ ] Ensure future saved bodies are always decoded
