### ISSUE TITLE
:bucket: Content Decoding

### ISSUE THREAD

**Issue by timolegros** [hicommonwealth/commonwealth#9183]
## Description
In the database we have multiple formats for thread/comment content:
- Plain text (markdown)
- Quill Deltas (ops)
- URI encoded text (markdown)
- URI encoded Quill Deltas (ops)

This is an insane mess that has resulted in custom encoding/decoding utils littered across the codebase.

In order to standardize content format we cannot use the plaintext column because Quill Deltas were incorrectly converted to plaintext by dropping all formatting (titles, italics, etc).

**_When this ticket is complete, all content should be stored in markdown format (plain text no special encoding)._**

## Tasks
- [x] https://github.com/hicommonwealth/commonwealth/issues/9182
- [x] https://github.com/hicommonwealth/commonwealth/issues/9168
- [x] https://github.com/hicommonwealth/commonwealth/issues/9169
- [x] https://github.com/hicommonwealth/commonwealth/issues/9167
- [x] https://github.com/hicommonwealth/commonwealth/issues/9184

## Additional context
This is a necessary precursor to #8661.
