### ISSUE TITLE
🪣 Domain Migration

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#9213]
## Description

This bucket will lay out the steps to migrate the commonwealth.im app to common.xyz.

## Project Owner

@jnaviask

### Phase 1
These tasks can be done at any time and must be completed before proceeding.

- [x] Add common.xyz to all whitelists/CORS policies: 
	- [x] Magic
	- [x] Alchemy
	- [x] OpenAI
	- [x] AWS
	- [x] Cosmos Directory
	- [x] Discord
	- [x] Cloudflare IPFS Proxy
	- [x] Cloudflare R2
	- [x] Cloudflare rate limiting/caching
	- [x] Unleash
	- [x] Prerender
- [x] Replace all string references to `commonwealth.im` with a variable
- [x] Create a `sitemap.common.xyz` S3 bucket + sub-domain on Cloudflare
- [x] @kurtisassad + @dillchen : for Magic V2 SSO Whitelist provisioning
- [x] Update marketing site (Webflow) to landing.common.xyz
- [x] Redirect `common.xyz/about` and other marketing site sub-pages to `landing.common.xyz/about`
- [x] Update/redirect `blog.commonwealth.im` to `blog.common.xyz`

### Phase 2
By this point, common.xyz should be fully functional and identical to commonwealth.im. This phase will transfer the core functionality to the new domain and should be executed as closely in time as possible.

- [x] Add common.xyz to heroku custom domains list + configure CNAME record on Cloudflare.
- [x] Set up 301 redirect from commonwealth.im to common.xyz
- [x] Update domain in Google Analytics console
- [x] Update hardcoded env vars on Heroku: `SERVER_URL`
- [x] Update `robots.txt` to use `sitemap.common.xyz` (#10220)
- [x] Update `PRODUCTION_DOMAIN` constant to `common.xyz` (#10220)
- [x] Replace externally stored API URLs: Snapshot Webhook (contact on TG), `common_api_url` on Knock
- [x] Run new sitemap generation

### Phase 3
By this point, common.xyz is the canonical domain for the application, and commonwealth.im is deprecated. These are lingering cleanup tasks.

- [x] Update documentation links: https://docs.common.xyz/commonwealth
- [x] Delete old sitemap bucket
- [x] Create new google search console for new domain. (see link, requires invite to be accepted) ([link](https://search.google.com/u/1/search-console/users?resource_id=sc-domain%3Acommon.xyz))
- [x] Rename s3 assets bucket.
- [x] ~~Update unleash, QA, and staging URLs to use common.xyz~~
- [x] Update Terms of Service URL and Privacy Policy URL on Discord
- [x] Update Mava, Datadog, Mixpanel
- [x] Add a link in Nav Bar to direct to About (landing.common.xyz) #10227 

## Open Questions
- Should renaming the s3 assets bucket happen in phase 1 or 2 instead of phase 3? i.e. is it MANDATORY to transition the canonical domain?
- What is scope of work required to update marketing site, as it is not managed by engineering?

**Comment by timolegros** [comment]
Tagging the following related tickets for context:
- https://github.com/hicommonwealth/commonwealth/issues/6091
- https://github.com/hicommonwealth/commonwealth/issues/8947
- https://github.com/hicommonwealth/commonwealth/issues/8017

**Comment by kurtisassad** [comment]
Assets are copied to:
assets.common.xyz

If we need to switch buckets, we should run:
aws s3 sync s3://assets.commonwealth.im s3://assets.common.xyz

To sync newly added assets and swap out the CNAME in cloudflare

**Comment by burtonator** [comment]
@dillchen we will also need to change our domain in google search tools.

under settings:

https://search.google.com/search-console/settings?resource_id=sc-domain%3Acommonwealth.im

We have to change this.

<img width="697" alt="image" src="https://github.com/user-attachments/assets/d9bd932d-603b-494d-b9a5-4c338993a65c">

The problem is that someone needs to be an owner, and I'm not an owner. 

https://support.google.com/webmasters/answer/7687615

... and here's how to use the change of address:

https://support.google.com/webmasters/answer/9370220?hl=en#tool_requirements

We also need to register a NEW google search console page for the new site which will hold all of our new stats.

**Comment by kurtisassad** [comment]
@kurtisassad Check cloudflare redirect rules for common.xyz/about and other paths and update here with info
